#!/usr/bin/env bash
#transfering a file to a server

if [ $# -lt 4 ]; then
    echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
    exit 1
fi

#assigning arguments to variables
file=$1
ip=$2
user=$3
path_to_ssh_key=$4

scp -o "StrictHostKeyChecking=no" -i "$path_to_ssh_key" "$file" "$user@$ip:~/"
