#!/usr/bin/env bash
#install nginx on a server and return a page
#that contains the string Hello World!
sudo apt-get -y update
sudo apt-get -y upgrade
sudo apt -y install nginx
sudo chown -R ubuntu /var/www/
echo "Hello World!" | sudo tee /var/www/html/index.

#start nginx
sudo service nginx start
