#!/usr/bin/env bash
#install nginx on a server and return a page
#that contains the string Hello World!
sudo apt-get -y update
sudo apt-get -y upgrade
sudo apt install -y nginx
sudo service nginx start
sudo ufw allow 'Nginx HTTP'
echo "Hello World!" | sudo tee /var/www/html/index.

#test nginx config
sudo nginx -t
sudo service nginx reload
