#!/usr/bin/env bash

# Update and upgrade system
sudo apt -y update
sudo apt -y upgrade

# Install Nginx
sudo apt -y install nginx

# Set permissions for /var/www/
sudo chown -R ubuntu /var/www/

# Create and populate index.html in /var/www/html
touch /var/www/html/index.html
echo "Hello World!" > /var/www/html/index.html

# Create 404.html in /var/www/html for custom error page
echo -e "Ceci n'est pas une page\n" > /var/www/html/404.html

# Configure Nginx: add redirection and custom headers
sudo sed -i "/^}$/i \ \n\tlocation /redirect_me {\n\t\treturn 301 https://www.github.com/AbdeljalilOuafi \n\t}\n" /etc/nginx/sites-enabled/default
sudo sed -i "/^}$/i \ \n\terror_page 404 /404.html;\n\tlocation = /404.html {\n\t\troot /var/www/html;\n\t\tinternal;\n\t\t\n\t}\n" /etc/nginx/sites-enabled/default
sudo sed -i "/^}$/i \ \n\tadd_header X-Served-By $HOSTNAME;\t\n" /etc/nginx/sites-enabled/default

# Restart Nginx to apply changes
sudo service nginx restart
