#!/usr/bin/env bash
#This script makes up a story using the info in /etc/passwd

while IFS=: read -r username pass uid gid gecos home shell; do
    echo "The user $username is part of the $gid gang, lives in $home and rides $shell. $uid place is protected by the passcode $pass, more info about the user here: $gecos"
done < "/etc/passwd"